### ISSUE TITLE
Mentions missing names

### ISSUE THREAD

**Issue by atalukder** [danielmbond/convert-slack-exports-to-html#2]
Hi Daniel,
The user names show up for comments by a user. But when someone uses a mention, it only shows @ sign. Similarly, when someone joins, it also shows @ signs.
examples:
10/24/2018 2:20:20 PM @ has joined the channel
10/24/2018 2:20:20 PM @ has joined the channel
10/24/2018 2:20:20 PM @ set the channel purpose: Q & A
Wonderful, thanks @

**Comment by danielmbond** [comment]
@atalukder I'm not seeing that, can you post the contents of the JSON file that you're seeing that happen on?
